#!/usr/bin/env node
/**
 * generateLocalGifManifest — v4.2.0 Theme B.
 *
 * Scans `assets/exercises/` for downloaded GIF/JPG/PNG files (one per
 * exerciseId) and emits `src/lib/localGifManifest.ts`. Each entry maps an
 * exerciseId to a `require()` call so Metro bundles the asset into the APK.
 *
 * Run after `curateExerciseGifs.js` (or whenever you've manually added /
 * updated bundled assets). Idempotent — safe to re-run.
 *
 * Usage:
 *   node scripts/generateLocalGifManifest.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ASSET_DIR = path.join(ROOT, 'assets', 'exercises');
const OUT_PATH = path.join(ROOT, 'src', 'lib', 'localGifManifest.ts');

// File extensions we treat as bundleable media. Order matters: the first
// matching extension for an exerciseId wins.
const EXT_PRIORITY = ['gif', 'webp', 'png', 'jpg', 'jpeg'];

function main() {
  if (!fs.existsSync(ASSET_DIR)) {
    console.warn(
      `assets/exercises/ does not exist — emitting empty manifest. ` +
      `Run \`node scripts/curateExerciseGifs.js\` first to populate it.`,
    );
    fs.mkdirSync(ASSET_DIR, { recursive: true });
  }

  // Build idsToFile = { 'push-up': 'push-up.gif', ... }
  const files = fs.existsSync(ASSET_DIR) ? fs.readdirSync(ASSET_DIR) : [];
  const byId = new Map();
  for (const file of files) {
    const m = file.match(/^([a-z0-9-]+)\.([a-z]+)$/i);
    if (!m) continue;
    const [, id, ext] = m;
    if (!EXT_PRIORITY.includes(ext.toLowerCase())) continue;
    const existing = byId.get(id);
    if (!existing) {
      byId.set(id, file);
      continue;
    }
    // Pick the higher-priority extension if duplicates exist.
    const existingExt = existing.split('.').pop().toLowerCase();
    if (EXT_PRIORITY.indexOf(ext.toLowerCase()) < EXT_PRIORITY.indexOf(existingExt)) {
      byId.set(id, file);
    }
  }

  const ids = Array.from(byId.keys()).sort();
  const lines = [
    '/**',
    ' * localGifManifest — v4.2.0 Theme B.',
    ' *',
    ' * AUTOGENERATED by scripts/generateLocalGifManifest.js — DO NOT EDIT.',
    ' *',
    ' * Maps exerciseId → Metro asset module reference for the bundled',
    ' * exercise GIFs in assets/exercises/. Local-first lookup happens in',
    ' * `resolveGif()` (src/lib/exerciseGifs.ts).',
    ' */',
    '',
    `// Generated ${new Date().toISOString()} from ${ids.length} bundled assets.`,
    '',
    'export const LOCAL_GIF_MANIFEST: Record<string, number> = {',
    ...ids.map((id) => `  '${id}': require('../../assets/exercises/${byId.get(id)}'),`),
    '};',
    '',
  ];

  fs.writeFileSync(OUT_PATH, lines.join('\n'));
  console.log(`Wrote ${OUT_PATH} (${ids.length} entries)`);
}

main();
